import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';import {frame,encode,Decoder} from './dist/codec.js';
const source=fs.readFileSync('dist/app.js','utf8').replace(/^import[^\n]*\n/,'');
function peer(role,live=true){const els=new Map();function el(id){if(!els.has(id))els.set(id,{value:({low:'20000',high:'21500',speed:'10',gain:'10',role,volume:'25%',direction:'A → B',distance:'30',device:role,scanRange:'20000',scanWidth:'1000',scanStep:'250',scanRepeats:'1'})[id]||'',style:{},dataset:{},attributes:{},classList:{toggle(){}},setAttribute(k,v){this.attributes[k]=v;},removeAttribute(k){delete this.attributes[k];},files:[],disabled:false,children:[],textContent:'',innerHTML:'',addEventListener(){},replaceChildren(...x){this.children=x;},append(...x){this.children.push(...x);},getContext(){return null;},clientWidth:0,clientHeight:0});return els.get(id);}
 const context={frame,encode,crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,Uint16Array,Float32Array,Blob,URL,performance,setTimeout:(fn,ms)=>setTimeout(fn,ms*.1),clearTimeout,requestAnimationFrame(){},cancelAnimationFrame(){},console,navigator:{userAgent:'synthetic protocol test'},localStorage:{getItem(){return null;},setItem(){}},document:{getElementById:el,querySelectorAll(){return[];},addEventListener(){},createElement:()=>({...el('dummy'),append(){},click(){}})},window:{addEventListener(){}},devicePixelRatio:1};vm.createContext(context);vm.runInContext(source+`\n globalThis.test={run,onPacket,frame,config,quickAction,chooseQuickRole,ui(id){return $(id);},setStart(fn){start=fn;},scanAll,scanBands,scanSummary,scanResult:()=>scanResult,rxScan:()=>rxScan,setControl(id,value){$(id).value=value;},setup(){ctx={sampleRate:48000,close(){}};stream={getTracks:()=>[]};started=true;receiver={port:{postMessage(){}}};listening=true;},setSend(fn){sendFrame=fn;},history(){return history;},received(){return $('received');}};`,context);if(live)context.test.setup();return context.test;}
const a=peer('tx'),b=peer('rx');let drop=true,ackCount=0;
function deliver(bytes,target,sender){let packet;const from=sender.config(),to=target.config();const pcm=encode(bytes,48000,from.ms,from.low,from.high,.1),pad=new Float32Array(pcm.length+4800);pad.set(pcm);const d=new Decoder(48000,to.ms,to.low,to.high,p=>packet=p);for(let i=0;i<pad.length;i+=128)d.push(pad.subarray(i,i+128));assert.ok(packet);target.onPacket(packet);}
a.setSend(async bytes=>{deliver(bytes,b,a);});b.setSend(async bytes=>{ackCount++;if(drop){drop=false;return;}deliver(bytes,a,b);});
await a.run('benchmark');const r=a.history().at(-1);assert.equal(r.success,3);assert.equal(r.retries,1);assert.equal(r.bytes,96);assert.ok(r.goodputBps>0);assert.equal(r.complete,true);
await a.run('text',new TextEncoder().encode('hello เสียง'),true);const file=a.history().at(-1);assert.equal(file.complete,true);assert.ok(file.goodputBps>0);assert.equal(b.received().hidden,false);
// Duplicate frames must get ACKed, while final content remains single.
const before=b.received().children.length;assert.equal(before,3);assert.ok(ackCount>=7);
console.log('Protocol checks passed: dropped ACK triggers retry, duplicates re-ACKed, benchmark goodput counts unique bytes, metadata/chunks/final SHA-256 handshake, received text.');

// Matched audio-only band negotiation, measure all planned windows, return to control.
assert.equal(a.scanBands(20000,21750,1000,500).at(-1).high,21750);
assert.equal(a.scanSummary({measurements:[]}),null);
assert.equal(a.scanSummary({measurements:[{goodputBps:0,success:0,attempted:2}]}).mean,0);
a.setControl('scanRange','20000');a.setControl('scanWidth','1000');a.setControl('scanStep','500');a.setControl('scanRepeats','1');
await a.scanAll();const survey=a.scanResult();assert.equal(survey.complete,true,survey.error);assert.equal(survey.bands.length,5);assert.ok(survey.bands.every(b=>b.measurements.length===1&&b.measurements[0].success===2));assert.equal(a.config().low,20000);assert.equal(a.config().high,21500);assert.equal(b.config().high,21500);assert.equal(b.rxScan(),null);
console.log('Frequency scan checks passed: all five planned windows negotiate over control audio, both peers retune together, 2 payload ACKs per window, return to control, untested distinct from measured zero.');

// The two visible primary actions complete the whole setup, with no extra mic/tab click.
const sender=peer('tx',false),listener=peer('rx',false);let senderOpens=0,listenerOpens=0;
sender.setStart(async()=>{senderOpens++;sender.setup();});listener.setStart(async()=>{listenerOpens++;listener.setup();});
sender.setSend(async bytes=>deliver(bytes,listener,sender));listener.setSend(async bytes=>deliver(bytes,sender,listener));
await listener.quickAction();assert.equal(listenerOpens,1);assert.equal(listener.ui('quickTitle').textContent,'Ready to receive');assert.equal(listener.ui('quickStart').disabled,true);assert.equal(listener.config().high,21000);assert.equal(listener.config().ms,40);
await sender.quickAction();assert.equal(senderOpens,1);assert.equal(sender.scanResult().complete,true);assert.equal(sender.ui('quickTitle').textContent,'Test complete');assert.equal(listener.ui('quickTitle').textContent,'Test received');assert.equal(sender.ui('quickStart').disabled,false);assert.equal(sender.ui('quickButtonText').textContent,'Test again');
const denied=peer('rx',false);denied.setStart(async()=>{throw Object.assign(new Error('permission denied'),{name:'NotAllowedError'});});await denied.quickAction();assert.equal(denied.ui('quickTitle').textContent,'Microphone permission needed');assert.equal(denied.ui('quickStart').disabled,false);assert.equal(denied.ui('quickButtonText').textContent,'Try again');
const alone=peer('tx',false);alone.setStart(async()=>alone.setup());alone.setSend(async()=>{});await alone.quickAction();assert.equal(alone.ui('quickTitle').textContent,'Receiver not found');assert.equal(alone.ui('quickStart').disabled,false);
console.log('Quick-start checks passed: receiver one press opens mic and waits; sender one press opens mic and scans all bands; completion reaches both devices; permission/absent-peer errors show an enabled retry action.');
